#!/usr/bin/env python3
"""
Regenerate Gotek_Touchscreen/webui.h from webui.html.

The device serves the configuration UI from a gzipped copy embedded in the
firmware, not from the SD card. That copy is a generated file, and until now
it was generated by hand — which meant it silently drifted: the committed
webui.h was several releases behind webui.html, so web-UI fixes were being
tagged and flashed without ever reaching the device.

Run this after ANY edit to webui.html, before building:

    python tools/make_webui_header.py

Verifies itself by decompressing what it just wrote and comparing byte for
byte against the source. --check exits non-zero if the header is stale
without modifying anything, which is what CI should call.
"""
from __future__ import annotations
import argparse
import gzip
import os
import re
import sys

REPO   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC    = os.path.join(REPO, "webui.html")
HEADER = os.path.join(REPO, "Gotek_Touchscreen", "webui.h")

BYTES_PER_LINE = 12


def compress(raw: bytes) -> bytes:
    # mtime=0 so identical input always produces an identical header —
    # otherwise every regeneration shows up as a diff and the file's
    # freshness becomes impossible to eyeball in review.
    return gzip.compress(raw, compresslevel=9, mtime=0)


def render(raw: bytes, blob: bytes) -> str:
    out = [
        "// Auto-generated from webui.html — do not edit manually.",
        "// Regenerate with: python tools/make_webui_header.py",
        f"// Source: {len(raw)} bytes, Gzipped: {len(blob)} bytes",
        f"const unsigned int webui_gz_len = {len(blob)};",
        "const unsigned char webui_gz[] PROGMEM = {",
    ]
    for i in range(0, len(blob), BYTES_PER_LINE):
        chunk = blob[i:i + BYTES_PER_LINE]
        out.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    out += ["};", ""]
    return "\n".join(out)


def embedded_blob(header_text: str) -> bytes:
    body = header_text.split("webui_gz[] PROGMEM = {", 1)
    if len(body) != 2:
        return b""
    return bytes(int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", body[1]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the header is current; do not write")
    args = ap.parse_args()

    if not os.path.isfile(SRC):
        print(f"error: {SRC} not found", file=sys.stderr)
        return 2

    raw = open(SRC, "rb").read()

    if args.check:
        if not os.path.isfile(HEADER):
            print("webui.h missing — run without --check")
            return 1
        current = embedded_blob(open(HEADER, encoding="utf-8", errors="replace").read())
        try:
            embedded = gzip.decompress(current) if current else b""
        except Exception:
            embedded = b""
        if embedded != raw:
            print(f"STALE: webui.h embeds {len(embedded)} bytes, webui.html is {len(raw)}")
            print("Run: python tools/make_webui_header.py")
            return 1
        print(f"webui.h is current ({len(raw)} bytes -> {len(current)} gzipped)")
        return 0

    blob = compress(raw)
    with open(HEADER, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(raw, blob))

    # Round-trip check: what the device will decompress must equal the source.
    written = embedded_blob(open(HEADER, encoding="utf-8").read())
    if gzip.decompress(written) != raw:
        print("error: round-trip verification FAILED", file=sys.stderr)
        return 3

    ratio = 100.0 * len(blob) / len(raw)
    print(f"webui.h regenerated: {len(raw)} bytes -> {len(blob)} gzipped ({ratio:.1f}%)")
    print("round-trip verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
