#!/usr/bin/env python3
"""
Compress an AmiCrush ADF into Gotek_Touchscreen/amicrush_adf.h so
firstBootScaffold() can drop it onto a fresh SD card.

    python tools/pack-amicrush.py [path/to/amicrush-fast.adf]

Default input is C:/Users/dimx/claude-sessions/amicrush-fast.adf — the
"fast" build produced by the AmiCrush project. Output is the C header
Gotek_Touchscreen/amicrush_adf.h, always in the same location. The
format is a zlib-wrapped deflate stream, unpacked at boot with miniz's
mz_uncompress (which ESP32-Arduino links via the OTA path).
"""
from __future__ import annotations
import os
import sys
import zlib

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_ADF = r"C:\Users\dimx\claude-sessions\amicrush-fast.adf"
HEADER = os.path.join(REPO, "Gotek_Touchscreen", "amicrush_adf.h")


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ADF
    if not os.path.isfile(src):
        print(f"error: not a file: {src}", file=sys.stderr)
        return 2

    with open(src, "rb") as fh:
        data = fh.read()
    raw_len = len(data)
    z = zlib.compress(data, 9)
    z_len = len(z)

    header = [
        "// Auto-generated by tools/pack-amicrush.py — DO NOT EDIT BY HAND.",
        f"// Source ADF: {os.path.basename(src)} ({raw_len} bytes uncompressed).",
        "// Format: zlib (deflate + zlib header). Unpack with miniz's",
        "// mz_uncompress() in firstBootScaffold on a fresh SD card.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define AMICRUSH_ADF_UNCOMPRESSED_LEN {raw_len}u",
        "",
        f"static const size_t amicrush_adf_z_len = {z_len}u;",
        "static const uint8_t amicrush_adf_z[] PROGMEM = {",
    ]
    for i in range(0, z_len, 16):
        header.append("  " + ", ".join(f"0x{b:02x}" for b in z[i:i + 16]) + ",")
    header.append("};")
    header.append("")

    with open(HEADER, "w", encoding="utf-8") as fh:
        fh.write("\n".join(header))

    print(f"raw = {raw_len:>8} bytes")
    print(f"gz  = {z_len:>8} bytes  ({100 * z_len / raw_len:.1f}% of raw)")
    print(f"wrote {HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
