#!/usr/bin/env python3
"""
Bundle the AmiCrush sample game (ADF + cover art) into PROGMEM headers
so firstBootScaffold() can drop them onto a fresh SD card.

Regenerates two headers under Gotek_Touchscreen/:

    amicrush_adf.h      zlib-compressed amicrush-fast.adf
    amicrush_cover.h    JPEG-encoded, resized cover art

Run:
    python tools/pack-amicrush.py [ADF] [COVER_PNG]

Defaults:
    ADF        C:/Users/dimx/claude-sessions/amicrush-fast.adf
    COVER_PNG  C:/Users/dimx/claude-sessions/assets/title.png

The cover is resized to fit inside 400x400 and re-encoded as JPEG at
quality 82 — the app already handles JPEG on both the list thumbnail
and the detail screen, and the smaller size keeps the firmware bin
below the ~3.1 MB APP slot.
"""
from __future__ import annotations
import io
import os
import sys
import zlib

from PIL import Image

REPO         = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_ADF  = r"C:\Users\dimx\claude-sessions\amicrush-fast.adf"
DEFAULT_ART  = r"C:\Users\dimx\claude-sessions\assets\title.png"
HDR_ADF      = os.path.join(REPO, "Gotek_Touchscreen", "amicrush_adf.h")
HDR_COVER    = os.path.join(REPO, "Gotek_Touchscreen", "amicrush_cover.h")

COVER_MAX  = 400
COVER_JPEG_QUALITY = 82


def write_header(path: str, name: str, data: bytes, meta_lines: list[str]) -> None:
    lines = [f"// Auto-generated by tools/pack-amicrush.py — DO NOT EDIT BY HAND."]
    lines += [f"// {m}" for m in meta_lines]
    lines += [
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"static const size_t {name}_len = {len(data)}u;",
        f"static const uint8_t {name}[] PROGMEM = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines += ["};", ""]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    adf_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ADF
    art_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_ART
    if not os.path.isfile(adf_path):
        print(f"error: ADF not found: {adf_path}", file=sys.stderr)
        return 2
    if not os.path.isfile(art_path):
        print(f"error: cover PNG not found: {art_path}", file=sys.stderr)
        return 2

    # ── ADF: zlib compress + PROGMEM header ──────────────────────────────
    adf = open(adf_path, "rb").read()
    adf_z = zlib.compress(adf, 9)
    lines = [
        f"// Source ADF: {os.path.basename(adf_path)} ({len(adf)} bytes uncompressed).",
        "// Format: zlib (deflate + zlib header). Unpack with the classic",
        "// zlib API's uncompress() — arduino-esp32 exposes it via its rom",
        "// glue (miniz's mz_uncompress is aliased as uncompress).",
    ]
    # We also need the uncompressed size at compile time to allocate the
    # PSRAM buffer; emit it as a preprocessor constant.
    header = [
        f"#define AMICRUSH_ADF_UNCOMPRESSED_LEN {len(adf)}u",
        "",
    ]
    # write_header writes only the array; we prepend the extra constant
    # manually so we don't need to complicate the shared helper.
    with open(HDR_ADF, "w", encoding="utf-8") as fh:
        pass  # truncate
    write_header(HDR_ADF, "amicrush_adf_z", adf_z, lines)
    # Reopen and insert the constant right after the trailing "#include"
    # block. We keep it simple by rewriting the file.
    with open(HDR_ADF, "r", encoding="utf-8") as fh:
        body = fh.read()
    body = body.replace(
        "#include <stdint.h>\n\n",
        "#include <stdint.h>\n\n" + "\n".join(header) + "\n",
        1,
    )
    with open(HDR_ADF, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"ADF   raw={len(adf):>7}  z={len(adf_z):>7}  ({100 * len(adf_z) / len(adf):.1f}%)")

    # ── Cover: resize + JPEG-encode + PROGMEM header ─────────────────────
    im = Image.open(art_path).convert("RGB")
    im.thumbnail((COVER_MAX, COVER_MAX), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=COVER_JPEG_QUALITY, optimize=True)
    jpg = buf.getvalue()
    write_header(
        HDR_COVER,
        "amicrush_cover_jpg",
        jpg,
        [
            f"Source: {os.path.basename(art_path)} ({im.width}x{im.height} after resize)",
            f"JPEG quality {COVER_JPEG_QUALITY}, {len(jpg)} bytes.",
        ],
    )
    print(f"cover     {im.width}x{im.height}  jpg={len(jpg):>7}")

    print()
    print(f"wrote {HDR_ADF}")
    print(f"wrote {HDR_COVER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
