#!/usr/bin/env python3
"""
Bundle the AmiCrush sample game (ADF + cover art) into PROGMEM headers
so firstBootScaffold() can drop them onto a fresh SD card.

Regenerates two headers under Gotek_Touchscreen/:

    amicrush_adf.h      raw amicrush-fast.adf as a PROGMEM byte array
    amicrush_cover.h    JPEG-encoded, resized cover art

Run:
    python tools/pack-amicrush.py [ADF] [COVER_PNG]

Defaults:
    ADF        C:/Users/dimx/claude-sessions/amicrush-fast.adf
    COVER_PNG  C:/Users/dimx/claude-sessions/assets/title.png

Why uncompressed for the ADF? arduino-esp32 declares uncompress() via
the ESP-IDF ROM headers but doesn't link the miniz implementation, so
a zlib blob would need us to ship an inflate implementation of our
own. Raw PROGMEM adds ~880 KB to the firmware bin (1.5 -> 2.4 MB),
still well under the ~3.1 MB APP slot on the default_8MB partition.
The cover PNG still gets resized + JPEG-encoded because it's an image
the app already knows how to decode; there's no equivalent trick to
avoid on that side.
"""
from __future__ import annotations
import io
import os
import sys

from PIL import Image

REPO         = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_ADF  = r"C:\Users\dimx\claude-sessions\amicrush-fast.adf"
DEFAULT_ART  = r"C:\Users\dimx\claude-sessions\assets\title.png"
HDR_ADF      = os.path.join(REPO, "Gotek_Touchscreen", "amicrush_adf.h")
HDR_COVER    = os.path.join(REPO, "Gotek_Touchscreen", "amicrush_cover.h")

COVER_MAX  = 400
COVER_JPEG_QUALITY = 82


def write_header(path: str, name: str, data: bytes, meta_lines: list[str]) -> None:
    lines = [f"// Auto-generated by tools/pack-amicrush.py — DO NOT EDIT BY HAND."]
    lines += [f"// {m}" for m in meta_lines]
    lines += [
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"static const size_t {name}_len = {len(data)}u;",
        f"static const uint8_t {name}[] PROGMEM = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines += ["};", ""]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    adf_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ADF
    art_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_ART
    if not os.path.isfile(adf_path):
        print(f"error: ADF not found: {adf_path}", file=sys.stderr)
        return 2
    if not os.path.isfile(art_path):
        print(f"error: cover PNG not found: {art_path}", file=sys.stderr)
        return 2

    # ── ADF: raw PROGMEM header ──────────────────────────────────────────
    adf = open(adf_path, "rb").read()
    lines = [
        f"// Source ADF: {os.path.basename(adf_path)} ({len(adf)} bytes).",
        "// Emitted verbatim as a PROGMEM array — firstBootScaffold copies",
        "// it byte-for-byte to /ADF/AmiCrush/AmiCrush.adf on a fresh SD.",
    ]
    write_header(HDR_ADF, "amicrush_adf", adf, lines)
    print(f"ADF   raw={len(adf):>7} bytes")

    # ── Cover: resize + JPEG-encode + PROGMEM header ─────────────────────
    im = Image.open(art_path).convert("RGB")
    im.thumbnail((COVER_MAX, COVER_MAX), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=COVER_JPEG_QUALITY, optimize=True)
    jpg = buf.getvalue()
    write_header(
        HDR_COVER,
        "amicrush_cover_jpg",
        jpg,
        [
            f"Source: {os.path.basename(art_path)} ({im.width}x{im.height} after resize)",
            f"JPEG quality {COVER_JPEG_QUALITY}, {len(jpg)} bytes.",
        ],
    )
    print(f"cover     {im.width}x{im.height}  jpg={len(jpg):>7}")

    print()
    print(f"wrote {HDR_ADF}")
    print(f"wrote {HDR_COVER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
